name 'ceph-chef'
maintainer 'Chris Jones'
maintainer_email 'cjones303@bloomberg.net'
license 'Apache2'
description 'Installs/Configures ceph-chef'
long_description 'Installs/Configures ceph-chef'
version '0.1.0'
