name 'ceph-helpers'
maintainer 'Chris Jones'
maintainer_email 'cjones303@bloomberg.net'
license 'Apache2'
description 'Installs/Configures ceph-helpers'
long_description 'Installs/Configures ceph-helpers'
version '0.1.0'
